export const SkillsData = [
  { skill: "TypeScript" },
  { skill: "React" },
  { skill: "CSS" },
  { skill: "Next.js" },
  { skill: "Redux" },
  { skill: "Web3 React" },
  { skill: "React Router Dom" },
  { skill: "Styled Components" },
  { skill: "Axios" },
  { skill: "Ethers" },
  { skill: "React Hook Form" },
  { skill: "Moralis" },
  { skill: "Hardhat" },
  { skill: "Typechain" },
  { skill: "Codegen" },
];
